In [33]:
import numpy as np
import sanity_funcs as sf

In [12]:
a=np.array([1,1,1,2,3,4])
b=np.array([2,2,2,1,4,3])
c=np.array([3,3,3,4,2,1])
d=np.array([4,4,4,3,1,2])

print(a,b,c,d)

[1 1 1 2 3 4] [2 2 2 1 4 3] [3 3 3 4 2 1] [4 4 4 3 1 2]


In [24]:
mat=np.array([a,b,c,d])
print(mat[0:4,1:5])

[[1 1 2 3]
 [2 2 1 4]
 [3 3 4 2]
 [4 4 3 1]]


In [29]:
sum=a+b+c+d
print(sum)

[10 10 10  9 15 16]


In [35]:
print(a)
print(sf.u1(a))
a+sf.u1(a)

[1 1 1 2 3 4]
[np.int64(1), np.int64(1), np.int64(2), np.int64(3), np.int64(1), np.int64(4)]


array([2, 2, 3, 5, 4, 8])